basic_beer:
    path: /beer/basic
    controller: App\Controller\BeerController::getBasicBeerAction

complete_beer:
    path: /beer/complete
    controller: App\Controller\BeerController::getCompleteBeerAction
