basic_beer:
    path: /basic/beer/
    controller: App\Controller\BeerController::getBasicBeerAction

complete_beer:
    path: /complete/beer/
    controller: App\Controller\BeerController::getCompleteBeerAction
